adsb:
  host: localhost
  port: 30003
spring:
  jooq.sql-dialect: H2
  datasource:
    url: jdbc:h2:~/adsb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    h2.console:
      enabled: true
      path: /h2-console